---
version: "3"
services:
  train:
    image: strangerjpb/train:latest
    ports:
      - 8000:80
  dth:
    image: strangerjpb/dth:latest
    ports:
      - 8001:80
  movies:
    image: strangerjpb/movies:latest
    ports:
      - 8002:80
